Repository TeamPOME/POME-Android, pull requests merged in 2022-07, with the labels that each got.

#7 [Feature/#6] asset 추가
  .idea/misc.xml
  app/build.gradle
  app/src/main/res/font/pretendard.xml
  app/src/main/res/font/pretendard_bold.otf
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: 💙안드최고아웃풋💙

#9 [Feature/#8] BottomNavigation 구현
  .idea/misc.xml
  app/src/main/java/com/teampome/pome/MainActivity.kt
  app/src/main/res/color/selector_bottom_navi.xml
  app/src/main/res/drawable/ic_friends.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_recollect.xml
  app/src/main/res/drawable/ic_record.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/strings.xml
Labels: feature, 💙안드최고아웃풋💙

#11 [Feature/#10] 회원가입 뷰 구현
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/presentation/login/SignUpActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/SignUpContentActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/SignViewModel.kt
  app/src/main/java/com/teampome/pome/util/BindingAdapter.kt
  app/src/main/res/drawable/cursor_custom.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_profile_empty.xml
  app/src/main/res/drawable/rectangle_grey_round_6.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up_content.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 💙안드최고아웃풋💙

#14 [Feature/#12] 친구추가 뷰 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/presentation/login/AddFriendActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/AddFriendAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/login/AddFriendData.kt
  app/src/main/java/com/teampome/pome/presentation/login/SignUpActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/SignUpContentActivity.kt
  app/src/main/res/drawable/ic_add_complete.xml
  app/src/main/res/drawable/ic_friend_profile.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_warning.xml
  app/src/main/res/drawable/rectangle_green_round_6.xml
  app/src/main/res/layout/activity_add_friend.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_sign_up_content.xml
  app/src/main/res/layout/item_friend_list.xml
  app/src/main/res/values/strings.xml
Labels: feature, 💙안드최고아웃풋💙

#16 Feature/#13
  .idea/.name
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/com/teampome/pome/MainActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/RecordFragment.kt
  app/src/main/res/drawable/ic_alarm_off.xml
  app/src/main/res/drawable/ic_empty_goal_3_d_component.xml
  app/src/main/res/drawable/ic_folder.xml
  app/src/main/res/drawable/ic_goal_category.xml
  app/src/main/res/drawable/ic_look_back.xml
  app/src/main/res/drawable/ic_look_back_right.xml
  app/src/main/res/drawable/ic_more_grey.xml
  app/src/main/res/drawable/ic_nothing.xml
  app/src/main/res/drawable/ic_pencil.xml
  app/src/main/res/drawable/rectangle_white_round_6.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/values/colors.xml
  build.gradle
Labels: feature, 💚안드일진리리드💚

#19 [feature/#15] Base Util 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/util/BaseActivity.kt
  app/src/main/java/com/teampome/pome/util/BaseFragment.kt
  app/src/main/java/com/teampome/pome/util/TimberInitializer.kt
Labels: 🤍안드수빈🤍, chore

#21 [Feature/#17] 기록 홈 UI 보완
  .idea/misc.xml
  app/src/main/java/com/teampome/pome/MainActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/RecordAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/record/RecordData.kt
  app/src/main/java/com/teampome/pome/presentation/record/RecordFragment.kt
  app/src/main/java/com/teampome/pome/util/CustomItemDecorator.kt
  app/src/main/java/com/teampome/pome/util/VerticalItemDecorator.kt
  app/src/main/res/color/selector_chip_background_color.xml
  app/src/main/res/color/selector_chip_text_color.xml
  app/src/main/res/drawable/ic_btn_make_goal.xml
  app/src/main/res/drawable/ic_emoji_background.xml
  app/src/main/res/drawable/ic_emoji_happy_mint_with_background.xml
  app/src/main/res/drawable/ic_folder.xml
  app/src/main/res/drawable/ic_lock_all.xml
  app/src/main/res/drawable/ic_question_with_background.xml
  app/src/main/res/drawable/seekbar_custom_green.xml
  app/src/main/res/drawable/seekbar_custom_pink.xml
  app/src/main/res/drawable/seekbar_custom_red.xml
  app/src/main/res/drawable/seekbar_thumb_custom_green.xml
  app/src/main/res/drawable/seekbar_thumb_custom_pink.xml
  app/src/main/res/drawable/seekbar_thumb_custom_red.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_record_list.xml
Labels: feature, 💚안드연진💚

#23 [Feature/#22] 기록 씀씀이 뷰 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/presentation/record/GoalLimitDialogFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/NoEmotionDialogFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/NoRecordDialogFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/RecordFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/RecordLookBackActivity.kt
  app/src/main/res/drawable/ic_3d_pen_mint.png
  app/src/main/res/drawable/ic_3d_pen_pink.png
  app/src/main/res/drawable/ic_3d_popper_pink.png
  app/src/main/res/drawable/ic_3d_trash_green.png
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_cancel_grey.xml
  app/src/main/res/drawable/ic_plus_with_background.xml
  app/src/main/res/drawable/ic_warning_alert_3_d_component.xml
  app/src/main/res/drawable/inset_dialog_background.xml
  app/src/main/res/drawable/rectangle_white_round_8.xml
  app/src/main/res/layout/activity_record_look_back.xml
  app/src/main/res/layout/fragment_goal_limit_dialog.xml
  app/src/main/res/layout/fragment_no_emotion_dialog.xml
  app/src/main/res/layout/fragment_no_record_dialog.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_record_list.xml
  app/src/main/res/values/strings.xml
Labels: feature, 💚안드연진💚

#28 [Feature/#24] 친구 탭 바텀시트 구현
  .idea/misc.xml
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsFragment.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsProfileAdapter.kt
  app/src/main/res/drawable/bottomsheet_round.xml
  app/src/main/res/drawable/ic_all_view_emoji_34.xml
  app/src/main/res/drawable/ic_emoji_smile_mint_34.xml
  app/src/main/res/layout/fragment_friends.xml
  app/src/main/res/layout/fragment_friends_bottom_sheet.xml
  app/src/main/res/layout/item_friend_profile_list.xml
  app/src/main/res/values/themes.xml
Labels: feature, 💜안드지영💜

#31 [Feature/#29] 친구 이모지 추가 구현
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsEmojiBalloon.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsFragment.kt
  app/src/main/res/drawable/balloon_custom.xml
  app/src/main/res/drawable/ic_emoji_flex_mint_28.xml
  app/src/main/res/drawable/ic_emoji_funny_mint_28.xml
  app/src/main/res/drawable/ic_emoji_happy_mint_28.xml
  app/src/main/res/drawable/ic_emoji_mint_flex_38.xml
  app/src/main/res/drawable/ic_emoji_mint_fun_38.xml
  app/src/main/res/drawable/ic_emoji_mint_heart_38.xml
  app/src/main/res/drawable/ic_emoji_mint_sad_38.xml
  app/src/main/res/drawable/ic_emoji_mint_smile_38.xml
  app/src/main/res/drawable/ic_emoji_mint_what_38.xml
  app/src/main/res/drawable/ic_emoji_sad_mint_28.xml
  app/src/main/res/drawable/ic_emoji_smile_mint_28.xml
  app/src/main/res/drawable/ic_emoji_what_mint_28.xml
  app/src/main/res/layout/item_emoji_balloon.xml
  app/src/main/res/layout/item_friend_consume_list.xml
  app/src/main/res/values/colors.xml
Labels: feature, 💜안드지영💜

#34 [Feature/#32] 회고탭 구현
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/presentation/main/MainActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordLookBackActivity.kt
  app/src/main/java/com/teampome/pome/presentation/remind/RemindConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFirstBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindSecondBottomSheetFragment.kt
  app/src/main/res/drawable/cly_custom.xml
  app/src/main/res/drawable/goal_custom.xml
  app/src/main/res/drawable/ic_emoji_happy_pink_34.xml
  app/src/main/res/drawable/ic_emoji_mint_heart_fiter_54.xml
  app/src/main/res/drawable/ic_emoji_mint_sad_filter_54.xml
  app/src/main/res/drawable/ic_emoji_mint_what_fiter_54.xml
  app/src/main/res/drawable/ic_emoji_pink_fiter_heart_54.xml
  app/src/main/res/drawable/ic_emoji_pink_fiter_sad_54.xml
  app/src/main/res/drawable/ic_emoji_pink_fiter_what_54.xml
  app/src/main/res/drawable/ic_emoji_sad_pink_34.xml
  app/src/main/res/drawable/ic_emoji_what_pink_34.xml
  app/src/main/res/drawable/ic_empty_goal.xml
  app/src/main/res/drawable/ic_filter_reset.xml
  app/src/main/res/drawable/ic_first_emotion_filter.xml
  app/src/main/res/drawable/ic_second_emotion_filter.xml
  app/src/main/res/drawable/ic_unlock.xml
  app/src/main/res/layout/fragment_remind.xml
  app/src/main/res/layout/fragment_remind_first_bottom_sheet.xml
  app/src/main/res/layout/fragment_remind_second_bottom_sheet.xml
  app/src/main/res/layout/item_remind_consume.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, 💜안드지영💜

#36 [Feature/#30] 회원가입 뷰 수정된 부분 반영
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/presentation/login/screens/SignUpActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/screens/SignUpBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/login/viewmodels/SignViewModel.kt
  app/src/main/res/drawable/ic_greypencil.xml
  app/src/main/res/drawable/ic_trash.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_sign_up_bottom_sheet.xml
  build.gradle
Labels: feature, 🤍안드수빈🤍

#39 [Feature/#35] 친구 및 회고 뷰 로직 수정
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsConsumeData.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsProfileAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsReactAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsEmojiBalloon.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFirstBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindSecondBottomSheetFragment.kt
  app/src/main/res/color/selector_chip_background_color.xml
  app/src/main/res/drawable/balloon_custom.xml
  app/src/main/res/layout/fragment_friends_bottom_sheet.xml
  app/src/main/res/layout/fragment_remind.xml
  app/src/main/res/layout/fragment_remind_first_bottom_sheet.xml
  app/src/main/res/layout/fragment_remind_second_bottom_sheet.xml
  app/src/main/res/layout/item_friend_consume_list.xml
  app/src/main/res/layout/item_friend_profile_list.xml
  app/src/main/res/layout/item_friends_emoji.xml
  app/src/main/res/layout/item_friends_reaction.xml
  app/src/main/res/values/chip_id.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, 💜안드지영💜

#40 [Feature/#37] 회원가입 서버통신을 위한 환경 설정
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/assets/fake_user.json
  app/src/main/java/com/teampome/pome/application/PomeApp.kt
  app/src/main/java/com/teampome/pome/data/remote/response/BaseResponse.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseUser.kt
  app/src/main/java/com/teampome/pome/data/remote/response/UserService.kt
  app/src/main/java/com/teampome/pome/data/repository/AuthRepository.kt
  app/src/main/java/com/teampome/pome/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/teampome/pome/data/repository/MockRepositoryImpl.kt
  app/src/main/java/com/teampome/pome/di/AppModule.kt
  app/src/main/java/com/teampome/pome/di/RepositoryModule.kt
  app/src/main/java/com/teampome/pome/presentation/login/screens/AddFriendActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/screens/SignUpActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/viewmodels/SignViewModel.kt
  app/src/main/java/com/teampome/pome/presentation/mypage/MarshMellowAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/mypage/MarshMellowData.kt
  app/src/main/java/com/teampome/pome/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/teampome/pome/presentation/mypage/SettingActivity.kt
  app/src/main/java/com/teampome/pome/util/FileParser.kt
  app/src/main/res/drawable/ic_badge.xml
  app/src/main/res/drawable/ic_level.xml
  app/src/main/res/drawable/ic_my_goal.xml
  app/src/main/res/drawable/ic_myprofile.xml
  app/src/main/res/drawable/ic_next.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/rectangle_pink_radius_6.xml
  app/src/main/res/drawable/selector_button.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_list_marshmellow.xml
Labels: feature, 🤍안드수빈🤍

#46 [Feature/#41] 이모직 클릭 관련
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/presentation/record/emotion/AfterSelectEmotionActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/emotion/SelectEmotionViewModel.kt
  app/src/main/java/com/teampome/pome/util/binding/BindingAdapter.kt
  app/src/main/res/color/selector_after_emotion_text.xml
  app/src/main/res/color/selector_before_emotion_text.xml
  app/src/main/res/layout/activity_after_select_emotion.xml
Labels: feature, 🤍안드수빈🤍

#50 [Feature/#49] 텍스트 셀렉터 적용 및 목표 추가 로직 확인
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/presentation/record/emotion/BeforeSelectEmotionActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/CalendarEndBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/CalendarStartBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalDateActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/viewmodels/GoalDateViewModel.kt
  app/src/main/res/layout/activity_after_select_emotion.xml
  app/src/main/res/layout/activity_before_select_emotion.xml
  app/src/main/res/layout/activity_goal_date.xml
Labels: feature, 💚안드연진💚

#52 [Feature/#47] 카카오 로그인을 위한 환경 설정
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/application/PomeApp.kt
  app/src/main/java/com/teampome/pome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teampome/pome/data/local/PomeDataStore.kt
  app/src/main/java/com/teampome/pome/di/AppModule.kt
  app/src/main/java/com/teampome/pome/presentation/login/screens/KakaoLoginActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/CalendarEndBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/CalendarStartBottomSheet.kt
  app/src/main/java/com/teampome/pome/util/ContextUtil.kt
  app/src/main/java/com/teampome/pome/util/UserApiClient.kt
  app/src/main/java/com/teampome/pome/util/decorate/MinMaxDecorator.kt
  app/src/main/res/drawable/ic_btn_kakao_login.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_logo_mint.xml
  app/src/main/res/drawable/ic_slogan_mint.xml
  app/src/main/res/drawable/kakao_marsh.png
  app/src/main/res/drawable/rectangle_yellow_round_6.xml
  app/src/main/res/layout/activity_kakao_login.xml
  app/src/main/res/values/colors.xml
Labels: feature, 🤍안드수빈🤍

#62 [Feature/#61] 목표 뷰 서버 붙이기 시작
  .idea/gradle.xml
  app/build.gradle
  app/src/main/java/com/teampome/pome/data/GoalService.kt
  app/src/main/java/com/teampome/pome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teampome/pome/data/remote/request/RequestGoalCreate.kt
  app/src/main/java/com/teampome/pome/data/remote/request/RequestRecordsCreate.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseGoalCreate.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseGoalDetail.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseGoalSave.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseRecordsCreate.kt
  app/src/main/java/com/teampome/pome/di/ServiceModule.kt
  app/src/main/java/com/teampome/pome/presentation/main/MainActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/adapters/GoalListAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/CalendarEndBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalDateActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalDetailActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalListBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordCalendarBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordWriteActivity.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/res/drawable/ic_unlock.xml
  app/src/main/res/drawable/selector_lock.xml
  app/src/main/res/layout/activity_record_write.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/layout_chip.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, 💚안드연진💚

#63 [Feature/#60] 친구 프로필 서버 연결
  app/src/main/java/com/teampome/pome/data/FriendService.kt
  app/src/main/java/com/teampome/pome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teampome/pome/data/remote/response/RequestFriendReaction.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseFriendsAll.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseFriendsProflie.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseReaction.kt
  app/src/main/java/com/teampome/pome/di/ServiceModule.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsConsumeData.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsProfileData.kt
  app/src/main/java/com/teampome/pome/presentation/friends/FriendsProfileInterface.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsProfileAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/RemindConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindReactionBottomSheet.kt
  app/src/main/res/layout/fragment_friends_bottom_sheet.xml
  app/src/main/res/layout/fragment_remind.xml
  app/src/main/res/layout/fragment_remind_reaction_bottom_sheet.xml
  app/src/main/res/layout/item_friend_consume_list.xml
Labels: feature, 💜안드지영💜

#66 [Feature/#59] 카카오 소셜로긘 , Splash 구현
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/teampome/pome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teampome/pome/data/local/PomeDataStore.kt
  app/src/main/java/com/teampome/pome/data/remote/response/RequestAuth.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseAuth.kt
  app/src/main/java/com/teampome/pome/data/remote/response/UserService.kt
  app/src/main/java/com/teampome/pome/data/repository/KaKaoRepository.kt
  app/src/main/java/com/teampome/pome/data/repository/KaKaoRepositoryImpl.kt
  app/src/main/java/com/teampome/pome/data/service/AuthService.kt
  app/src/main/java/com/teampome/pome/di/RepositoryModule.kt
  app/src/main/java/com/teampome/pome/di/ServiceModule.kt
  app/src/main/java/com/teampome/pome/presentation/login/SplashActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/screens/KakaoLoginActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/viewmodels/KaKaoViewModel.kt
  app/src/main/java/com/teampome/pome/util/ViewUtil.kt
  app/src/main/res/drawable/big_marshmallow.png
  app/src/main/res/drawable/ic_logo.xml
  app/src/main/res/drawable/ic_mashmallow_is_yours.xml
  app/src/main/res/layout/activity_kakao_login.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/themes.xml
Labels: feature, 🤍안드수빈🤍

#67 [Feature/#65] 친구 및 회고 탭 서버 연결
  app/src/main/java/com/teampome/pome/data/FriendService.kt
  app/src/main/java/com/teampome/pome/data/RemindService.kt
  app/src/main/java/com/teampome/pome/data/remote/request/RequestFriendAddReaction.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseFriendReaction.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseFriendsAll.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseRemindData.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseRemindGoal.kt
  app/src/main/java/com/teampome/pome/di/ServiceModule.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsProfileAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsReactAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/RemindConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/res/drawable/ic_question_backgorund_34.xml
  app/src/main/res/layout/fragment_remind.xml
  app/src/main/res/layout/item_friend_consume_list.xml
  app/src/main/res/layout/item_remind_consume.xml
Labels: feature, 💜안드지영💜

#70 [Feature/#68] 친구 검색 및 추가 뷰 서버 통신
  app/src/main/java/com/teampome/pome/data/FriendService.kt
  app/src/main/java/com/teampome/pome/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/teampome/pome/data/remote/request/RequestFriendsData.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseFriendsData.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsFragment.kt
  app/src/main/java/com/teampome/pome/presentation/login/AddFriendAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/login/screens/AddFriendActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/screens/KakaoLoginActivity.kt
  app/src/main/java/com/teampome/pome/presentation/login/viewmodels/KaKaoViewModel.kt
  app/src/main/res/layout/activity_add_friend.xml
  app/src/main/res/layout/item_friend_list.xml
Labels: feature, 🤍안드수빈🤍

#72 [Feature/#69] 친구 탭 및 회고 탭 서버 연결
  .idea/gradle.xml
  app/src/main/java/com/teampome/pome/data/FriendService.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ReactInfo.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseFriendReaction.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseRemindData.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseRemindGoal.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsProfileAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsReactAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/RemindConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/remind/adapters/RemindReactionAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFirstBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindReactionBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindSecondBottomSheetFragment.kt
  app/src/main/res/drawable/ic_emoji_flex_mint_28_overlay.xml
  app/src/main/res/drawable/ic_emoji_funny_mint_28_overlay.xml
  app/src/main/res/drawable/ic_emoji_happy_mint_28_overlay.xml
  app/src/main/res/drawable/ic_emoji_sad_mint_28_overlay.xml
  app/src/main/res/drawable/ic_emoji_smile_mint_28_overlay.xml
  app/src/main/res/drawable/ic_emoji_what_mint_28_overlay.xml
  app/src/main/res/layout/item_friend_consume_list.xml
  app/src/main/res/layout/item_remind_consume.xml
Labels: feature, 💜안드지영💜

#73 [Feature/#71] POME 앱 로고 및 서비스 명 변경
  app/src/main/AndroidManifest.xml
  app/src/main/pome-playstore.png
  app/src/main/res/mipmap-anydpi-v26/pome.xml
  app/src/main/res/mipmap-anydpi-v26/pome_round.xml
  app/src/main/res/mipmap-hdpi/pome.png
  app/src/main/res/mipmap-hdpi/pome_foreground.png
  app/src/main/res/mipmap-hdpi/pome_round.png
  app/src/main/res/mipmap-mdpi/pome.png
  app/src/main/res/mipmap-mdpi/pome_foreground.png
  app/src/main/res/mipmap-mdpi/pome_round.png
  app/src/main/res/mipmap-xhdpi/pome.png
  app/src/main/res/mipmap-xhdpi/pome_foreground.png
  app/src/main/res/mipmap-xhdpi/pome_round.png
  app/src/main/res/mipmap-xxhdpi/pome.png
  app/src/main/res/mipmap-xxhdpi/pome_foreground.png
  app/src/main/res/mipmap-xxhdpi/pome_round.png
  app/src/main/res/mipmap-xxxhdpi/pome.png
  app/src/main/res/mipmap-xxxhdpi/pome_foreground.png
  app/src/main/res/mipmap-xxxhdpi/pome_round.png
  app/src/main/res/values/pome_background.xml
Labels: feature, 🤍안드수빈🤍

#74 Feature/#64
  app/src/main/java/com/teampome/pome/data/RecordsService.kt
  app/src/main/java/com/teampome/pome/data/remote/response/Records.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseRecordsLook.kt
  app/src/main/java/com/teampome/pome/di/ServiceModule.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/GoalListData.kt
  app/src/main/java/com/teampome/pome/presentation/record/RecordAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/record/adapters/GoalListAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/record/emotion/BeforeSelectEmotionActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalListBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordAddActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordCalendarBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordWriteActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/viewmodels/RecordWriteViewModel.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/res/drawable/ic_emoji_happy_mint_56_with_background.xml
  app/src/main/res/drawable/ic_emoji_sad_mint_56_with_background.xml
  app/src/main/res/drawable/ic_emoji_what_mint_56_with_background.xml
  app/src/main/res/drawable/shape_dday_badge.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_record_write.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/item_record_list.xml
  app/src/main/res/values/strings.xml
Labels: feature, 💚안드연진💚, refactor

#78 [Feature/#77] 모든 뷰 setOnSignleListener로 변경
  .idea/gradle.xml
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/login/AddFriendAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/DeleteGoalDialogFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/DeleteRecordDialogFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalAddActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalDateActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalDetailActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalLimitDialogFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalListBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/NoRecordDialogFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordAddActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordCalendarBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordLookBackActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordWriteActivity.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFirstBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
Labels: feature, 🤍안드수빈🤍

#80 [Feature/#75] 목표 삭제 구현
  app/src/main/java/com/teampome/pome/data/GoalService.kt
  app/src/main/java/com/teampome/pome/presentation/record/RecordAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/DeleteGoalDialogFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalDeleteBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/viewmodels/GoalIdViewModel.kt
  app/src/main/res/layout/fragment_delete_goal_dialog.xml
  app/src/main/res/layout/fragment_goal_delete_bottom_sheet.xml
Labels: feature, 💚안드연진💚

#81 [Feature/#76] 기록 및 회고 레이아웃 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/res/drawable/seekbar_custom_pink.xml
  app/src/main/res/drawable/seekbar_custom_red.xml
  app/src/main/res/layout/fragment_friends.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_remind.xml
  app/src/main/res/values/strings.xml
Labels: feature, 💜안드지영💜

#82 [Feature/#79] 마이페이지 서버 통신
  app/src/main/java/com/teampome/pome/data/FriendService.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseMyUser.kt
  app/src/main/java/com/teampome/pome/presentation/mypage/MyPageFragment.kt
  app/src/main/res/drawable/ic_level3.xml
  app/src/main/res/drawable/ic_level4.xml
  app/src/main/res/drawable/ic_level_badge.xml
  app/src/main/res/drawable/ic_levelup.xml
  app/src/main/res/drawable/ic_record_level.xml
  app/src/main/res/drawable/ic_tag_level.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature, 🤍안드수빈🤍

#84 [Feature/#83] 돌아볼 씀씀이 뷰 서버 연결
  app/src/main/java/com/teampome/pome/data/RecordsService.kt
  app/src/main/java/com/teampome/pome/data/remote/response/RecordsBack.kt
  app/src/main/java/com/teampome/pome/data/remote/response/ResponseRecordsLookBack.kt
  app/src/main/java/com/teampome/pome/presentation/record/adapters/RecordLookBackAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/record/emotion/AfterSelectEmotionActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordLookBackActivity.kt
  app/src/main/res/layout/activity_record_look_back.xml
  app/src/main/res/layout/item_record_look_list.xml
  app/src/main/res/values/strings.xml
Labels: feature, 💚안드연진💚

#88 [Feature/#87] 친구 바텀시트 이모지 필터링
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/adapters/FriendsReactAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsBottomSheetFragment.kt
  app/src/main/res/drawable/ic_emoji_flex_mint_34_click.xml
  app/src/main/res/drawable/ic_emoji_funny_mint_34_click.xml
  app/src/main/res/drawable/ic_emoji_heart_mint_34_click.xml
  app/src/main/res/drawable/ic_emoji_sad_mint_34_click.xml
  app/src/main/res/drawable/ic_emoji_smile_mint_34_click.xml
  app/src/main/res/drawable/ic_emoji_what_mint_34_click.xml
  app/src/main/res/drawable/ic_emoji_whole_grey_34.xml
  app/src/main/res/layout/fragment_friends.xml
  app/src/main/res/layout/fragment_friends_bottom_sheet.xml
  app/src/main/res/layout/item_friend_consume_list.xml
  app/src/main/res/values/strings.xml
Labels: feature, 💜안드지영💜

#89 [Feature/#86] 서버 연결 코루틴 적용
  app/src/main/java/com/teampome/pome/data/GoalService.kt
  app/src/main/java/com/teampome/pome/data/RecordsService.kt
  app/src/main/java/com/teampome/pome/presentation/record/emotion/BeforeSelectEmotionActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/goal/GoalDetailActivity.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/GoalListBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordFragment.kt
  app/src/main/java/com/teampome/pome/presentation/record/screens/RecordLookBackActivity.kt
  app/src/main/res/values/colors.xml
Labels: 💚안드연진💚, refactor

#93 [Feature/#91] 회고 탭 필터링 구현
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/friends/screens/FriendsFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/RemindConsumeAdapter.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFirstBottomSheetFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindFragment.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindReactionBottomSheet.kt
  app/src/main/java/com/teampome/pome/presentation/remind/screens/RemindSecondBottomSheetFragment.kt
  app/src/main/res/drawable/cly_custom.xml
  app/src/main/res/drawable/ic_arrow_down_17.xml
  app/src/main/res/drawable/rectangle_friendconsume.xml
  app/src/main/res/drawable/textview_background_custom.xml
  app/src/main/res/layout/fragment_remind.xml
  app/src/main/res/layout/fragment_remind_first_bottom_sheet.xml
  app/src/main/res/layout/fragment_remind_reaction_bottom_sheet.xml
  app/src/main/res/layout/fragment_remind_second_bottom_sheet.xml
Labels: feature, 💜안드지영💜
